export interface AdetPrimRow {
  stokKodu:     string
  kategori:     string | null
  bayiMerch:    number | null
  kosulluDestek: number | null
}

export const ADET_PRIM_DEFAULTS: AdetPrimRow[] = [
  { stokKodu: 'EP71AB14UG',  kategori: null, bayiMerch: 150, kosulluDestek: 100 },
  { stokKodu: 'EP71UB14DB',  kategori: null, bayiMerch: 150, kosulluDestek: 100 },
  { stokKodu: 'EP72AB21UG',  kategori: null, bayiMerch: 150, kosulluDestek: 100 },
  { stokKodu: 'EP72H21WET',  kategori: null, bayiMerch: 150, kosulluDestek: 100 },
  { stokKodu: 'EP72UB21SW',  kategori: null, bayiMerch: 150, kosulluDestek: 100 },
  { stokKodu: 'EP82AB25UG',  kategori: null, bayiMerch: 250, kosulluDestek: 150 },
  { stokKodu: 'EP82H25WET',  kategori: null, bayiMerch: 250, kosulluDestek: 150 },
  { stokKodu: 'EP82UB25UG',  kategori: null, bayiMerch: 250, kosulluDestek: 150 },
  { stokKodu: 'EP83HB25UV',  kategori: null, bayiMerch: 250, kosulluDestek: 100 },
  { stokKodu: 'ER71HW1UG',  kategori: null, bayiMerch: 250, kosulluDestek: 100 },
  { stokKodu: 'ER71UW2SW',  kategori: null, bayiMerch: 250, kosulluDestek: 100 },
  { stokKodu: 'ER81UW3SW',  kategori: null, bayiMerch: 350, kosulluDestek: 100 },
  { stokKodu: 'EW51U1DB',  kategori: null, bayiMerch: 200, kosulluDestek: 100 },
  { stokKodu: 'E5KM1-4SWB',  kategori: null, bayiMerch: 250, kosulluDestek: 100 },
  { stokKodu: 'E5KM1-6GBP',  kategori: null, bayiMerch: 250, kosulluDestek: 100 },
  { stokKodu: 'E6AF1-4ST',  kategori: null, bayiMerch: null, kosulluDestek: null },
  { stokKodu: 'E6AF1-6ST',  kategori: null, bayiMerch: 75,  kosulluDestek: null },
  { stokKodu: 'E8SI2-8OG',  kategori: null, bayiMerch: 75,  kosulluDestek: 75  },
  { stokKodu: 'E8ST2-8OG',  kategori: null, bayiMerch: 250, kosulluDestek: 100 },
  { stokKodu: 'EUFC82EB',  kategori: null, bayiMerch: 250, kosulluDestek: 125 },
  { stokKodu: 'EUFC8ALRGY',  kategori: null, bayiMerch: 150, kosulluDestek: 125 },
  { stokKodu: 'EUFC8ANIMA',  kategori: null, bayiMerch: null, kosulluDestek: null },
  { stokKodu: 'EUOC94DB',  kategori: null, bayiMerch: 200, kosulluDestek: 50  },
  { stokKodu: 'EUOC9GREEN',  kategori: null, bayiMerch: null, kosulluDestek: null },
  { stokKodu: 'PC91-8STM',  kategori: null, bayiMerch: 350, kosulluDestek: 150 },
  { stokKodu: 'PC91-ALRG',  kategori: null, bayiMerch: 350, kosulluDestek: 150 },
  { stokKodu: 'PD82-ALRG',  kategori: null, bayiMerch: 350, kosulluDestek: 100 },
  { stokKodu: 'RC6925',  kategori: null, bayiMerch: 100, kosulluDestek: 50  },
  { stokKodu: 'RC6932',  kategori: null, bayiMerch: 100, kosulluDestek: 50  },
  { stokKodu: 'RC9525',  kategori: null, bayiMerch: 100, kosulluDestek: 50  },
  { stokKodu: 'RC9532',  kategori: null, bayiMerch: 100, kosulluDestek: 50  },
  { stokKodu: 'RC9588',  kategori: null, bayiMerch: 100, kosulluDestek: 50  },
  { stokKodu: 'RC9535',  kategori: null, bayiMerch: 100, kosulluDestek: 50  },
  { stokKodu: 'RS6600',  kategori: null, bayiMerch: 100, kosulluDestek: 50  },
  { stokKodu: 'RS6625',  kategori: null, bayiMerch: 100, kosulluDestek: 50  },
  { stokKodu: 'RS6700',  kategori: null, bayiMerch: 100, kosulluDestek: 50  },
  { stokKodu: 'RS9500',  kategori: null, bayiMerch: 100, kosulluDestek: 50  },
  { stokKodu: 'RS9505',  kategori: null, bayiMerch: 100, kosulluDestek: 50  },
  { stokKodu: 'RBS2000',  kategori: null, bayiMerch: null, kosulluDestek: null },
  { stokKodu: 'RBS4000',  kategori: null, bayiMerch: 150, kosulluDestek: 50  },
  { stokKodu: 'RBS6000',  kategori: null, bayiMerch: 150, kosulluDestek: 100 },
  { stokKodu: 'REP9548G',  kategori: null, bayiMerch: 150, kosulluDestek: 100 },
  { stokKodu: 'REP9548P',  kategori: null, bayiMerch: 150, kosulluDestek: 100 },
  { stokKodu: 'REP9542',  kategori: null, bayiMerch: 100, kosulluDestek: 50  },
  { stokKodu: 'REP5736',  kategori: null, bayiMerch: null, kosulluDestek: null },
  { stokKodu: 'RFX8500',  kategori: null, bayiMerch: 100, kosulluDestek: 50  },
  { stokKodu: 'RHC6800',  kategori: null, bayiMerch: 50,  kosulluDestek: 50  },
  { stokKodu: 'RPG6500',  kategori: null, bayiMerch: 50,  kosulluDestek: 50  },
  { stokKodu: 'RPG6700',  kategori: null, bayiMerch: 50,  kosulluDestek: 50  },
  { stokKodu: 'RPG7500',  kategori: null, bayiMerch: 100, kosulluDestek: 50  },
  { stokKodu: 'RRS8700',  kategori: null, bayiMerch: 100, kosulluDestek: 50  },
  { stokKodu: 'IPL9500',  kategori: null, bayiMerch: 100, kosulluDestek: null },
  { stokKodu: 'IPL9650',  kategori: null, bayiMerch: 150, kosulluDestek: 75  },
  { stokKodu: 'IPL9750',  kategori: null, bayiMerch: 250, kosulluDestek: 125 },
  { stokKodu: 'IPL9850',  kategori: null, bayiMerch: 300, kosulluDestek: 150 },
  { stokKodu: 'IPL9950',  kategori: null, bayiMerch: 300, kosulluDestek: 150 },
  { stokKodu: 'RAF7000',  kategori: null, bayiMerch: 200, kosulluDestek: 100 },
  { stokKodu: 'RHB7130',  kategori: null, bayiMerch: 150, kosulluDestek: 100 },
  { stokKodu: 'RTM3000',  kategori: null, bayiMerch: 100, kosulluDestek: null },
  { stokKodu: 'RTM3200',  kategori: null, bayiMerch: 100, kosulluDestek: 75  },
  { stokKodu: 'RTM5200',  kategori: null, bayiMerch: 150, kosulluDestek: 100 },
  { stokKodu: 'AS8200P',  kategori: null, bayiMerch: 150, kosulluDestek: 100 },
  { stokKodu: 'AS8200B',  kategori: null, bayiMerch: 150, kosulluDestek: 100 },
  { stokKodu: 'AS8700',  kategori: null, bayiMerch: 200, kosulluDestek: 100 },
  { stokKodu: 'RHD2200',  kategori: null, bayiMerch: null, kosulluDestek: null },
  { stokKodu: 'RHD6165G',  kategori: null, bayiMerch: 150, kosulluDestek: 100 },
  { stokKodu: 'RHD6165W',  kategori: null, bayiMerch: 150, kosulluDestek: 100 },
  { stokKodu: 'RHD9190B',  kategori: null, bayiMerch: 200, kosulluDestek: 125 },
  { stokKodu: 'RHD9190W',  kategori: null, bayiMerch: 200, kosulluDestek: 125 },
  { stokKodu: 'RHS9000B',  kategori: null, bayiMerch: 250, kosulluDestek: 150 },
  { stokKodu: 'RHS9000P',  kategori: null, bayiMerch: 250, kosulluDestek: 150 },
  { stokKodu: 'RHS8900P',  kategori: null, bayiMerch: 200, kosulluDestek: null },
  { stokKodu: 'RHS8900B',  kategori: null, bayiMerch: 200, kosulluDestek: null },
  { stokKodu: 'RMS9200B',  kategori: null, bayiMerch: 350, kosulluDestek: 250 },
  { stokKodu: 'RMS9200P',  kategori: null, bayiMerch: 350, kosulluDestek: 250 },
]

/** Map: stokKodu → { bayiMerch, kosulluDestek } for fast lookup */
export const PRIM_MAP_DEFAULT = new Map(
  ADET_PRIM_DEFAULTS.map(r => [r.stokKodu, r])
)
